# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM Dry Run

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
      - name: Publish to NPM
        run: npm publish --access public --dry-run
